import Footer from "@/components/Footer";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import { Inter } from "next/font/google";
import "../public/output.css";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <HeroSection />

        <main>
          <!-- Product section start -->
          <section class="w-11/12 lg:w-10/12 max-w-7xl mx-auto py-10">
            <div class="grid grid-cols-2 md:grid-cols-3 gap-4 lg:grid-cols-4 my-4 lg:my-10">
              <!-- Product 1 Start -->
              <div>
                <div
                  class="relative delay-150 w-180px lg:w-[270px] h-[205px] lg:h-[310px] bg-[#f8f8f8] bg-[url('./assets/products/iphone.jpg')] bg-cover bg-center transition-all duration-3000 ease-in-out transform">
                </div>
                <h2 class="text-sm lg:text-base mt-2">
                  <a class="text-base font-bold" href="./productPage.html">
                    iPhone 9
                  </a>
                  <span class="text-[#919090]">
                    <a href="./category.html">(Smartphones)</a>
                  </span>
                </h2>
                <p class="text-[#919090] text-sm ">An apple mobile which is nothing like apple</p>

                <p class="text-rose-600 text-sm mt-4"><span class="text-[#919090] line-through">$205.00</span> $195.00</p>
              </div>
              <!-- Product 1 End -->

              <!-- Product 2 Start -->
              <div>
                <div
                  class="relative delay-150 w-180px lg:w-[270px] h-[205px] lg:h-[310px] bg-[#f8f8f8] bg-[url('./assets/products/macbook-pro.png')] bg-cover bg-center transition-all duration-3000 ease-in-out transform">
                </div>
                <h2 class="text-sm lg:text-base mt-2">
                  <a class="text-base font-bold" href="./productPage.html">
                    MacBook Pro
                  </a>
                  <span class="text-[#919090]">
                    <a href="./category.html">(Laptops)</a>
                  </span>
                </h2>
                <p class="text-[#919090] text-sm ">MacBook Pro 2021 with mini-LED display may launch between September,
                  November</p>

                <p class="text-rose-600 text-sm mt-4"><span class="text-[#919090] line-through">$205.00</span> $195.00</p>
              </div>
              <!-- Product 2 End -->

              <!-- Product 3 Start -->
              <div>
                <div
                  class="relative delay-150 w-180px lg:w-[270px] h-[205px] lg:h-[310px] bg-[#f8f8f8] bg-[url('./assets/products/samsung-galaxy-book.jpg')] bg-cover bg-center transition-all duration-3000 ease-in-out transform">
                </div>
                <h2 class="text-sm lg:text-base mt-2">
                  <a class="text-base font-bold" href="./productPage.html">
                    Samsung Galaxy Book
                  </a>
                  <span class="text-[#919090]">
                    <a href="./category.html">(Laptops)</a>
                  </span>
                </h2>
                <p class="text-[#919090] text-sm ">Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM
                  Launched</p>

                <p class="text-rose-600 text-sm mt-4"><span class="text-[#919090] line-through">$205.00</span> $195.00</p>
              </div>
              <!-- Product 3 End -->

              <!-- Product 4 Start -->
              <div>
                <div
                  class="relative delay-150 w-180px lg:w-[270px] h-[205px] lg:h-[310px] bg-[#f8f8f8] bg-[url('./assets/products/perfume.jpg')] bg-cover bg-center transition-all duration-3000 ease-in-out transform">
                </div>
                <h2 class="text-sm lg:text-base mt-2">
                  <a class="text-base font-bold" href="./productPage.html">
                    Brown Perfume
                  </a>
                  <span class="text-[#919090]">
                    <a href="./category.html">(Fragrances)</a>
                  </span>
                </h2>
                <p class="text-[#919090] text-sm ">Royal_Mirage Sport Brown Perfume for Men & Women - 120ml</p>

                <p class="text-rose-600 text-sm mt-4"><span class="text-[#919090] line-through">$205.00</span> $195.00</p>
              </div>
              <!-- Product 4 End -->
              <!-- Product 1 Start -->
              <div>
                <div
                  class="relative delay-150 w-180px lg:w-[270px] h-[205px] lg:h-[310px] bg-[#f8f8f8] bg-[url('./assets/products/iphone.jpg')] bg-cover bg-center transition-all duration-3000 ease-in-out transform">
                </div>
                <h2 class="text-sm lg:text-base mt-2">
                  <a class="text-base font-bold" href="./productPage.html">
                    iPhone 9
                  </a>
                  <span class="text-[#919090]">
                    <a href="./category.html">(Smartphones)</a>
                  </span>
                </h2>
                <p class="text-[#919090] text-sm ">An apple mobile which is nothing like apple</p>

                <p class="text-rose-600 text-sm mt-4"><span class="text-[#919090] line-through">$205.00</span> $195.00</p>
              </div>
              <!-- Product 1 End -->

              <!-- Product 2 Start -->
              <div>
                <div
                  class="relative delay-150 w-180px lg:w-[270px] h-[205px] lg:h-[310px] bg-[#f8f8f8] bg-[url('./assets/products/macbook-pro.png')] bg-cover bg-center transition-all duration-3000 ease-in-out transform">
                </div>
                <h2 class="text-sm lg:text-base mt-2">
                  <a class="text-base font-bold" href="./productPage.html">
                    MacBook Pro
                  </a>
                  <span class="text-[#919090]">
                    <a href="./category.html">(Laptops)</a>
                  </span>
                </h2>
                <p class="text-[#919090] text-sm ">MacBook Pro 2021 with mini-LED display may launch between September,
                  November</p>

                <p class="text-rose-600 text-sm mt-4"><span class="text-[#919090] line-through">$205.00</span> $195.00</p>
              </div>
              <!-- Product 2 End -->

              <!-- Product 3 Start -->
              <div>
                <div
                  class="relative delay-150 w-180px lg:w-[270px] h-[205px] lg:h-[310px] bg-[#f8f8f8] bg-[url('./assets/products/samsung-galaxy-book.jpg')] bg-cover bg-center transition-all duration-3000 ease-in-out transform">
                </div>
                <h2 class="text-sm lg:text-base mt-2">
                  <a class="text-base font-bold" href="./productPage.html">
                    Samsung Galaxy Book
                  </a>
                  <span class="text-[#919090]">
                    <a href="./category.html">(Laptops)</a>
                  </span>
                </h2>
                <p class="text-[#919090] text-sm ">Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM
                  Launched</p>

                <p class="text-rose-600 text-sm mt-4"><span class="text-[#919090] line-through">$205.00</span> $195.00</p>
              </div>
              <!-- Product 3 End -->

              <!-- Product 4 Start -->
              <div>
                <div
                  class="relative delay-150 w-180px lg:w-[270px] h-[205px] lg:h-[310px] bg-[#f8f8f8] bg-[url('./assets/products/perfume.jpg')] bg-cover bg-center transition-all duration-3000 ease-in-out transform">
                </div>
                <h2 class="text-sm lg:text-base mt-2">
                  <a class="text-base font-bold" href="./productPage.html">
                    Brown Perfume
                  </a>
                  <span class="text-[#919090]">
                    <a href="./category.html">(Fragrances)</a>
                  </span>
                </h2>
                <p class="text-[#919090] text-sm ">Royal_Mirage Sport Brown Perfume for Men & Women - 120ml</p>

                <p class="text-rose-600 text-sm mt-4"><span class="text-[#919090] line-through">$205.00</span> $195.00</p>
              </div>
              <!-- Product 4 End -->
              <!-- Product 1 Start -->
              <div>
                <div
                  class="relative delay-150 w-180px lg:w-[270px] h-[205px] lg:h-[310px] bg-[#f8f8f8] bg-[url('./assets/products/iphone.jpg')] bg-cover bg-center transition-all duration-3000 ease-in-out transform">
                </div>
                <h2 class="text-sm lg:text-base mt-2">
                  <a class="text-base font-bold" href="./productPage.html">
                    iPhone 9
                  </a>
                  <span class="text-[#919090]">
                    <a href="./category.html">(Smartphones)</a>
                  </span>
                </h2>
                <p class="text-[#919090] text-sm ">An apple mobile which is nothing like apple</p>

                <p class="text-rose-600 text-sm mt-4"><span class="text-[#919090] line-through">$205.00</span> $195.00</p>
              </div>
              <!-- Product 1 End -->

              <!-- Product 2 Start -->
              <div>
                <div
                  class="relative delay-150 w-180px lg:w-[270px] h-[205px] lg:h-[310px] bg-[#f8f8f8] bg-[url('./assets/products/macbook-pro.png')] bg-cover bg-center transition-all duration-3000 ease-in-out transform">
                </div>
                <h2 class="text-sm lg:text-base mt-2">
                  <a class="text-base font-bold" href="./productPage.html">
                    MacBook Pro
                  </a>
                  <span class="text-[#919090]">
                    <a href="./category.html">(Laptops)</a>
                  </span>
                </h2>
                <p class="text-[#919090] text-sm ">MacBook Pro 2021 with mini-LED display may launch between September,
                  November</p>

                <p class="text-rose-600 text-sm mt-4"><span class="text-[#919090] line-through">$205.00</span> $195.00</p>
              </div>
              <!-- Product 2 End -->

              <!-- Product 3 Start -->
              <div>
                <div
                  class="relative delay-150 w-180px lg:w-[270px] h-[205px] lg:h-[310px] bg-[#f8f8f8] bg-[url('./assets/products/samsung-galaxy-book.jpg')] bg-cover bg-center transition-all duration-3000 ease-in-out transform">
                </div>
                <h2 class="text-sm lg:text-base mt-2">
                  <a class="text-base font-bold" href="./productPage.html">
                    Samsung Galaxy Book
                  </a>
                  <span class="text-[#919090]">
                    <a href="./category.html">(Laptops)</a>
                  </span>
                </h2>
                <p class="text-[#919090] text-sm ">Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM
                  Launched</p>

                <p class="text-rose-600 text-sm mt-4"><span class="text-[#919090] line-through">$205.00</span> $195.00</p>
              </div>
              <!-- Product 3 End -->

              <!-- Product 4 Start -->
              <div>
                <div
                  class="relative delay-150 w-180px lg:w-[270px] h-[205px] lg:h-[310px] bg-[#f8f8f8] bg-[url('./assets/products/perfume.jpg')] bg-cover bg-center transition-all duration-3000 ease-in-out transform">
                </div>
                <h2 class="text-sm lg:text-base mt-2">
                  <a class="text-base font-bold" href="./productPage.html">
                    Brown Perfume
                  </a>
                  <span class="text-[#919090]">
                    <a href="./category.html">(Fragrances)</a>
                  </span>
                </h2>
                <p class="text-[#919090] text-sm ">Royal_Mirage Sport Brown Perfume for Men & Women - 120ml</p>

                <p class="text-rose-600 text-sm mt-4"><span class="text-[#919090] line-through">$205.00</span> $195.00</p>
              </div>
              <!-- Product 4 End -->
            </div>
          </section>
          <!-- Product section start -->
          <section class="bg-[#ced3ca] py-5 lg:py-16">
            <div class="w-10/12 lg:w-4/12 mx-auto">
              <h1 class="italic text-xl lg:text-3xl font-serif my-5 text-center">Get the inside scoop</h1>
              <p class="text-center text-sm lg:text-base">
                Sign up for new product drops, behind-the-scenes content, and monthly "5 Things I'm Digging" emails
              </p>
              <form action="#" class="mb-5">
                <input type="text" class="p-3 mt-10 border border-black focus:outline-none w-full"
                  placeholder="Enter your email" />
                <button class="w-full bg-[#1a1a1a] hover:bg-[#3a3a3a] text-center py-2 mt-2 text-white">
                  See what we're doing
                </button>
              </form>
            </div>
          </section>
        </main>
        {children}
        <Footer />
      </body>
    </html>
  );
}
